
# This is a quick function I wrote to make using pytest easier to use.
# It works by taking the list of tests generated by calling 
# `pytest --collect-only`, and then feeding it to fzf, which allows you to
# select the test(s) to run and pass them to pytest itself.
# This script supports calling test based on unit test name, test class, test 
# file, or test directory.
function pyt {
  local fzf_bind=
  case "$1" in
    test | t)
      pytest --collect-only --quiet     \
        | grep '[^:]\+::[^:]\+::[^:]\+' \
        | fzf -i                        \
              --reverse                 \
              --height ~50%             \
              --delimiter ::            \
              --bind 'enter:become(pytest -W ignore::DeprecationWarning {1}::{2}::{3})'
      ;;
    class | c)
      pytest --collect-only --quiet                              \
        | grep '[^:]\+::[^:]\+::[^:]\+'                          \
        | sed 's/^\([^:]\+\)::\([^:]\+\)::\([^:]\+\).*$/\1::\2/' \
        | sort --unique                                          \
        | fzf -i                                                 \
              --reverse                                          \
              --height ~50%                                      \
              --delimiter ::                                     \
              --bind 'enter:become(pytest -W ignore::DeprecationWarning {1}::{2})'
      ;;
    file | f | module | m)
      pytest --collect-only --quiet                          \
        | grep '[^:]\+::[^:]\+::[^:]\+'                      \
        | sed 's/^\([^:]\+\)::\([^:]\+\)::\([^:]\+\).*$/\1/' \
        | sort --unique                                      \
        | fzf -i                                             \
              --reverse                                      \
              --height ~50%                                  \
              --delimiter ::                                 \
              --bind 'enter:become(pytest -W ignore::DeprecationWarning {1})'
      ;;
    directory | dir | d)
      pytest --collect-only --quiet                          \
        | grep '[^:]\+::[^:]\+::[^:]\+'                      \
        | sed 's/^\([^:]\+\)::\([^:]\+\)::\([^:]\+\).*$/\1/' \
        | xargs dirname                                      \
        | sort --unique                                      \
        | fzf -i                                             \
              --reverse                                      \
              --height ~50%                                  \
              --delimiter ::                                 \
              --bind 'enter:become(pytest -W ignore::DeprecationWarning {1})'
      ;;
    *)
      echo 'Use one of:'
      echo '  function func fn'
      echo '  class c'
      echo '  file f module m'
      echo '  directory dir d'
    ;;
  esac
}
